services:
  wildfly:
    build:
      context: ./wildfly
    container_name: wildfly
    restart: unless-stopped
    ports:
      - "8888:8080"
      - "9999:9990"
    networks:
      - backend

  websphere:
    build:
      context: ./websphere
    container_name: websphere
    restart: unless-stopped    
    ports:
      - "9080:9080"
      - "9443:9443"
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wildfly
      - websphere
    networks:
      - backend

networks:
  backend:
    driver: bridge
