services:
  wildfly:
    build:
      context: ./wildfly
    container_name: wildfly
    ports:
      - "8888:8080"
      - "9999:9990"
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wildfly
    networks:
      - backend

networks:
  backend:
    driver: bridge
